name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"
          cache: "pnpm"

      - run: pnpm install
      - uses: actions/cache@v4
        with:
          path: .moon/cache
          key: ${{ runner.os }}-moon-docs
      - run: moon run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
